//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace verklega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineTranslations
    {
        public int ID { get; set; }
        public int SL_ID { get; set; }
        public int U_ID { get; set; }
        public int L_ID { get; set; }
        public string Text { get; set; }
    
        public virtual Languages Languages { get; set; }
        public virtual SubtitleLines SubtitleLines { get; set; }
        public virtual Users Users { get; set; }
    }
}
