//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace verklega.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VERK014_H36Entities : DbContext
    {
        public VERK014_H36Entities()
            : base("name=VERK014_H36Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<LineTranslations> LineTranslations { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<SubtitleLines> SubtitleLines { get; set; }
        public virtual DbSet<Subtitles> Subtitles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
