//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace verklega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subtitles
    {
        public Subtitles()
        {
            this.Requests = new HashSet<Requests>();
            this.SubtitleLines = new HashSet<SubtitleLines>();
        }
    
        public int ID { get; set; }
        public int U_ID { get; set; }
        public int L_ID { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
    
        public virtual Languages Languages { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
        public virtual ICollection<SubtitleLines> SubtitleLines { get; set; }
        public virtual Users Users { get; set; }
    }
}
