//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace verklega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubtitleLines
    {
        public SubtitleLines()
        {
            this.LineTranslations = new HashSet<LineTranslations>();
        }
    
        public int ID { get; set; }
        public int S_ID { get; set; }
        public string Start { get; set; }
        public string Duration { get; set; }
    
        public virtual ICollection<LineTranslations> LineTranslations { get; set; }
        public virtual Subtitles Subtitles { get; set; }
    }
}
