//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace verklega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.LineTranslations = new HashSet<LineTranslations>();
            this.Requests = new HashSet<Requests>();
            this.Subtitles = new HashSet<Subtitles>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
    
        public virtual ICollection<LineTranslations> LineTranslations { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
        public virtual ICollection<Subtitles> Subtitles { get; set; }
    }
}
